name: unsplash_client
description: Simple Flutter App showing trending images from Unsplash (https://unsplash.com/).
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  # for icons
  cupertino_icons: '^0.1.2'
  # share images
  share: '^0.6.0'
  # display images in staggered grid
  flutter_staggered_grid_view: '^0.2.7'
  # open url for an image
  url_launcher: '^5.0.2'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
