name: unsplash_client
description: Simple Flutter App showing trending images from Unsplash (https://unsplash.com/).
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  # display images in staggered grid
  flutter_staggered_grid_view: ^0.2.7
  # open url for an image
  url_launcher: ^5.0.2
  # image loading
  cached_network_image: ^0.7.0
  # zoom images
  photo_view: ^0.2.2
  # format date
  date_format: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
