name: unsplash_client
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

  path_provider: ^0.3.1

  share: ^0.3.1

  flutter_staggered_grid_view: ^0.1.0

  url_launcher: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
      - family: Roboto Mono
        fonts:
          # https://fonts.google.com/specimen/Roboto+Mono
          - asset: fonts/RobotoMono-Regular.ttf
